# Generated by Django 3.2.9 on 2021-12-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuenta', '0002_carteraahorro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField()),
                ('valor', models.IntegerField()),
                ('Cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuenta.carteraahorro')),
            ],
        ),
    ]
