# Generated by Django 3.2.9 on 2021-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuenta', '0003_ingresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoEgreso', models.IntegerField()),
                ('TipoEgreso', models.CharField(max_length=100)),
            ],
        ),
    ]
