# Generated by Django 3.2.9 on 2021-12-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuenta', '0006_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteraahorro',
            name='idPerfil',
            field=models.IntegerField(null=True),
        ),
    ]
