# Generated by Django 3.2.9 on 2021-12-06 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DineroEfectivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteraAhorro',
            fields=[
                ('idCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('TipoCartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DineroEfectivo.tipocarteraahorro')),
            ],
        ),
    ]
