# Generated by Django 3.2.9 on 2021-12-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DineroEfectivo', '0002_carteraahorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteraahorro',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
