# Generated by Django 3.2.9 on 2021-12-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DineroEfectivo', '0004_ingresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
