# Generated by Django 3.2.9 on 2021-12-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DineroEfectivo', '0005_tipoegreso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoEgreso',
        ),
    ]
