# Generated by Django 3.2.9 on 2021-12-06 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DineroEfectivo', '0007_tipoegreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.IntegerField()),
                ('Cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DineroEfectivo.carteraahorro')),
                ('TipoEgreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DineroEfectivo.tipoegreso')),
            ],
        ),
    ]
