# Generated by Django 3.2.9 on 2021-12-06 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DineroEfectivo', '0009_auto_20211205_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoEgreso', models.IntegerField()),
                ('TipoEgreso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField()),
                ('valor', models.IntegerField()),
                ('Cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DineroEfectivo.carteraahorro')),
            ],
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField()),
                ('valor', models.IntegerField()),
                ('Cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DineroEfectivo.carteraahorro')),
                ('TipoEgreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DineroEfectivo.tipoegreso')),
            ],
        ),
    ]
